-- Seed cemeteries (run after schema.sql)
insert into public.cemeteries (
  id, name, name_ar, commune, commune_ar, wilaya,
  address, address_ar, lat, lng,
  opening_hours, opening_hours_ar, hectares,
  type, type_ar, description, description_ar, image_url, available
) values
(
  'el-alia',
  'Cimetière d''El Alia',
  'مقبرة العالية',
  'Bab Ezzouar',
  'باب الزوار',
  'Alger',
  'Route nationale 5, El Alia, Bab Ezzouar',
  'الطريق الوطني رقم 5، العالية، باب الزوار',
  36.7267, 3.1933,
  '08:00 – 17:00',
  '08:00 – 17:00',
  58,
  'islamique',
  'إسلامي',
  'L''un des plus grands cimetières de la wilaya d''Alger, situé dans la commune de Bab Ezzouar. Un espace paysager entretenu avec soin.',
  'واحدة من أكبر المقابر في ولاية الجزائر، تقع في بلدية باب الزوار. مساحة ذات مناظر طبيعية يتم الاعتناء بها بعناية.',
  '',
  true
),
(
  'sidi-mhamed',
  'Cimetière de Sidi M''Hamed',
  'مقبرة سيدي امحمد',
  'Sidi M''Hamed',
  'سيدي امحمد',
  'Alger',
  'Rue Hassiba Ben Bouali, Sidi M''Hamed',
  'شارع حسيبة بن بوعلي، سيدي امحمد',
  36.7608, 3.0535,
  '08:00 – 17:00',
  '08:00 – 17:00',
  32,
  'islamique',
  'إسلامي',
  'Cimetière historique au cœur de la capitale, entretenu quotidiennement par les équipes de l''EGPFC.',
  'مقبرة تاريخية في قلب العاصمة، تتم صيانتها يوميًا من قبل فرق المؤسسة.',
  '',
  true
),
(
  'el-kettar',
  'Cimetière d''El Kettar',
  'مقبرة القطار',
  'Oued Koriche',
  'وادي قريش',
  'Alger',
  'Boulevard Abderrezak Hahad, Oued Koriche',
  'شارع عبد الرزاق حاحاد، وادي قريش',
  36.7858, 3.0416,
  '08:00 – 17:00',
  '08:00 – 17:00',
  45,
  'islamique',
  'إسلامي',
  'Cimetière emblématique surplombant la baie d''Alger, offrant un cadre paysager exceptionnel.',
  'مقبرة رمزية تطل على خليج الجزائر، توفر إطارًا طبيعيًا استثنائيًا.',
  '',
  true
),
(
  'el-madania',
  'Cimetière d''El Madania',
  'مقبرة المدنية',
  'El Madania',
  'المدنية',
  'Alger',
  'Chemin des cimetières, El Madania',
  'طريق المقابر، المدنية',
  36.7457, 3.0697,
  '08:00 – 17:00',
  '08:00 – 17:00',
  28,
  'islamique',
  'إسلامي',
  'Cimetière paisible situé sur les hauteurs d''El Madania avec une vue panoramique.',
  'مقبرة هادئة تقع على مرتفعات المدنية بإطلالة بانورامية.',
  '',
  true
),
(
  'kouba',
  'Cimetière de Kouba',
  'مقبرة القبة',
  'Kouba',
  'القبة',
  'Alger',
  'Rue Mohamed Belkacemi, Kouba',
  'شارع محمد بلقاسمي، القبة',
  36.7333, 3.0833,
  '08:00 – 17:00',
  '08:00 – 17:00',
  22,
  'islamique',
  'إسلامي',
  'Cimetière communal bien entretenu au cœur de la commune de Kouba.',
  'مقبرة بلدية بحالة جيدة في قلب بلدية القبة.',
  '',
  true
),
(
  'bir-mourad',
  'Cimetière de Bir Mourad Raïs',
  'مقبرة بئر مراد رايس',
  'Bir Mourad Raïs',
  'بئر مراد رايس',
  'Alger',
  'Rue des frères Zaghloul, Bir Mourad Raïs',
  'شارع الإخوة زغلول، بئر مراد رايس',
  36.7413, 3.0451,
  '08:00 – 17:00',
  '08:00 – 17:00',
  19,
  'islamique',
  'إسلامي',
  'Cimetière de Bir Mourad Raïs, espace de recueillement soigneusement entretenu.',
  'مقبرة بئر مراد رايس، فضاء للتأمل يتم صيانته بعناية.',
  '',
  true
),
(
  'bologhine',
  'Cimetière de Bologhine',
  'مقبرة بولوغين',
  'Bologhine',
  'بولوغين',
  'Alger',
  'Rue Abderrahmane Arbadji, Bologhine',
  'شارع عبد الرحمن عرباجي، بولوغين',
  36.8043, 3.0351,
  '08:00 – 17:00',
  '08:00 – 17:00',
  26,
  'islamique',
  'إسلامي',
  'Cimetière historique de Bologhine, proche de la Basilique Notre-Dame d''Afrique.',
  'مقبرة تاريخية في بولوغين، قرب كنيسة السيدة الإفريقية.',
  '',
  true
),
(
  'hussein-dey',
  'Cimetière de Hussein Dey',
  'مقبرة حسين داي',
  'Hussein Dey',
  'حسين داي',
  'Alger',
  'Rue Tripoli, Hussein Dey',
  'شارع طرابلس، حسين داي',
  36.7447, 3.0987,
  '08:00 – 17:00',
  '08:00 – 17:00',
  31,
  'islamique',
  'إسلامي',
  'Cimetière principal de Hussein Dey, espace vert entretenu au sein du tissu urbain.',
  'المقبرة الرئيسية لحسين داي، مساحة خضراء معتنى بها داخل النسيج الحضري.',
  '',
  true
)
on conflict (id) do update set
  name = excluded.name,
  name_ar = excluded.name_ar,
  commune = excluded.commune,
  commune_ar = excluded.commune_ar,
  address = excluded.address,
  address_ar = excluded.address_ar,
  lat = excluded.lat,
  lng = excluded.lng,
  opening_hours = excluded.opening_hours,
  opening_hours_ar = excluded.opening_hours_ar,
  hectares = excluded.hectares,
  type = excluded.type,
  type_ar = excluded.type_ar,
  description = excluded.description,
  description_ar = excluded.description_ar,
  updated_at = now();
